project:
  type: website

website:
  title: "msdial5tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - chapter1.qmd
      - chapter2.qmd
      - chapter3.qmd
      - chapter4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



